---

- name: install RDS feature web access
  ansible.windows.win_feature:
    name: 
    - RDS-WEB-ACCESS
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: winfeature 

- name: reboot if required
  ansible.windows.win_reboot:
  when: winfeature.reboot_required
