---

- name: install RDS feature sessionhost
  ansible.windows.win_feature:
    name: 
    - RDS-RD-SERVER
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: winfeature

- name: reboot if required
  ansible.windows.win_reboot:
  when: winfeature.reboot_required 

