---

- name: install RDS features
  ansible.windows.win_feature:
    name: 
    - RDS-RD-SERVER
    - RDS-CONNECTION-BROKER
    - RDS-WEB-ACCESS
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: reboot if required
  ansible.windows.win_reboot:
  when: win_feature.reboot_required
